sudo: required
services :
  - docker

before_install :
  - docker build -t faizalnur/dockerreacts -f Dockerfile.dev .

  script:
  - docker run -e CI=true faizalnur/dockerreacts npm run test -- --coverage
 