version: "3"
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: 'reactweb' 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: 'reactweb_test' 
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm","run","test"]